name: cli-ci

on:
  push:
    paths:
      - ".github/workflows/subspace-cli-release.yml"
      - ".github/workflows/cli-ci.yml"
      - ".github/workflows/reusable-cli-registry-ci.yml"
      - "tooling/subspace-cli/**"
      - "**/*.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches:
      - dev
      - main
  merge_group:
    branches:
      - dev
      - main

permissions:
  contents: read

jobs:
  test:
    name: Registry CLI CI
    uses: ./.github/workflows/reusable-cli-registry-ci.yml
    with:
      build_binary: true
      binary_output_path: /tmp/subspace-cli
      run_smoke_test: true
      upload_binary_artifact: false
